# Generated by Django 4.1 on 2022-09-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pedido Confirmado", "Accepted"),
                    ("Pedido Recusado", "Denied"),
                    ("Seu pedido está sendo analisado", "Default"),
                ],
                default="Seu pedido está sendo analisado",
                max_length=50,
            ),
        ),
    ]
